repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        additional_dependencies: [flake8]
        files: ^finance-backend/app/  # Да, имеенно с апострофом, чтобы прогонялся весь код в app

  # - repo: local
  #   hooks:
  #     - id: unittests
  #       name: run unit tests
  #       entry: python -m unittest
  #       language: system
  #       pass_filenames: false
  #       args: ["discover", "tests"]