name: Test
on:
  push:
    branches:
          - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Change Directory
        run: ls -la
      - name: install deps
        run: poetry insatll
      - name: test
        run: poetry run pytest
